server:
  port: 9090
spring:
  application:
    name: GATEWAY-ZUUL-01
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8762:8762/eureka/,http://eureka8761:8761/eureka/


zuul:
  routes:
    hello:
      path: /001/**
      serviceId: eureka-provider-01
    user:
      path: /002/**
      serviceId: eureka-provider-01